Add a CI check for version mismatches

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,9 +25,22 @@ jobs:
     with:
       pre-commit-source: pre-commit
 
+  verify-min-os-version:
+    name: Verify min_os_version
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - run: |
+          target_windows_build=$(grep -oP 'target_windows_build = \K\d+' "{{ cookiecutter.format }}/briefcase.toml")
+          min_os_version=$(grep -oP '"min_os_version": "\K\d+(?=")' "cookiecutter.json")
+          if [ "$target_windows_build" -ne "$min_os_version" ]; then
+              echo "::error::$target_windows_build != $min_os_version"
+              exit 1
+          fi
+
   verify-apps:
     name: Build apps
-    needs: pre-commit
+    needs: [pre-commit, verify-min-os-version]
     uses: beeware/.github/.github/workflows/app-build-verify.yml@main
     with:
       python-version: ${{ matrix.python-version }}
